// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: chat.proto

package grpcgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chatting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendUserId    int32                  `protobuf:"varint,1,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"`
	RecvUserId    int32                  `protobuf:"varint,2,opt,name=recv_user_id,json=recvUserId,proto3" json:"recv_user_id,omitempty"`
	Msg           *Msg                   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chatting) Reset() {
	*x = Chatting{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chatting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chatting) ProtoMessage() {}

func (x *Chatting) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chatting.ProtoReflect.Descriptor instead.
func (*Chatting) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Chatting) GetSendUserId() int32 {
	if x != nil {
		return x.SendUserId
	}
	return 0
}

func (x *Chatting) GetRecvUserId() int32 {
	if x != nil {
		return x.RecvUserId
	}
	return 0
}

func (x *Chatting) GetMsg() *Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Chatting) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x06grpcgo\x1a\rmessage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x01\n" +
	"\bChatting\x12 \n" +
	"\fsend_user_id\x18\x01 \x01(\x05R\n" +
	"sendUserId\x12 \n" +
	"\frecv_user_id\x18\x02 \x01(\x05R\n" +
	"recvUserId\x12\x1d\n" +
	"\x03msg\x18\x03 \x01(\v2\v.grpcgo.MsgR\x03msg\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04timeB!Z\x1fgithub.com/ShreyasJenner/grpcgob\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chat_proto_goTypes = []any{
	(*Chatting)(nil),              // 0: grpcgo.Chatting
	(*Msg)(nil),                   // 1: grpcgo.Msg
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_chat_proto_depIdxs = []int32{
	1, // 0: grpcgo.Chatting.msg:type_name -> grpcgo.Msg
	2, // 1: grpcgo.Chatting.time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	file_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
